# LSTM with Time Series Generator

In [22]:
from utilities.std_imports import *
from utilities.tf_imports import *

### Generate data

In [46]:
ts = np.arange(100)
ts

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Define ts generator

In [52]:
tsGen = tkp.sequence.TimeseriesGenerator(ts, ts, length=6, batch_size=8)
tsGen[0]

(array([[ 0,  1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5,  6],
        [ 2,  3,  4,  5,  6,  7],
        [ 3,  4,  5,  6,  7,  8],
        [ 4,  5,  6,  7,  8,  9],
        [ 5,  6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10, 11],
        [ 7,  8,  9, 10, 11, 12]]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13]))

### Build and fit model

In [65]:
model = tkm.Sequential()
model.add(tkl.Dense(12, activation='relu', input_dim=6))
model.add(tkl.Dense(8, activation='relu', input_dim=6))
model.add(tkl.Dense(1))
model.compile(optimizer='adam', loss='mse')

model.fit(tsGen, steps_per_epoch=1, epochs=1000, verbose=0)

### Prediction

In [67]:
x_input = np.array([9,10,11,12,13,14]).reshape((1, 6))
pred = model.predict(x_input, verbose=0)
pred[0][0]

13.22582

### Credits & Links

https://keras.io/api/preprocessing/timeseries/  
https://machinelearningmastery.com/how-to-use-the-timeseriesgenerator-for-time-series-forecasting-in-keras/